name: Tenable Cloud Security ASPM Scan
on:
  push:
    branches: [ "main","master" ]
  pull_request:
    branches: [ "main","master" ]

jobs:
  tenable-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Tenable Cloud Security Enterprise Scan
        uses: tenable/cloud-security-actions/iac@v1 
        with:
          apiToken: ${{ secrets.TENABLE_API_TOKEN }}
          apiUrl: ${{ secrets.TENABLE_API_URL }}
          failOnMinSeverity: 'high'
          logs: true
